# Generated by Django 3.0.3 on 2020-11-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
    ]
